# -*- mode: ruby -*-
# vim: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_check_update = true
     
    config.vm.define "server" do |s|
      s.vm.hostname = 'server'
      s.vm.network "private_network", ip: "10.0.0.10", netmask: "255.255.255.0" , adapter: 2,  virtualbox__intnet: "vpn"
      s.vm.network "private_network", ip: "10.1.1.1", netmask: "255.255.255.0" , adapter: 3,  virtualbox__intnet: "ras1"
      s.vm.provider :virtualbox do |v|
      v.name = "server"
      end
  
    end
    
    config.vm.define "client" do |c|
        c.vm.hostname = 'client'
        c.vm.network "private_network", ip: "10.0.0.30", netmask: "255.255.255.0" , adapter: 2,  virtualbox__intnet: "vpn"
        c.vm.network "private_network", ip: "10.1.2.1", netmask: "255.255.255.0" , adapter: 3,  virtualbox__intnet: "ras2"
        c.vm.provider :virtualbox do |v|
        v.name = "client"
        end
    
      end
   
    config.vm.provision "ansible" do |ansible|ra
      ansible.playbook = "./playbook3.yml"
      ansible.become = "true"
   end
    
  end