---
  - name: inetRouter config
    hosts: inetRouter
    become: true

    tasks:
      - name: route add 1
        shell: echo "192.168.0.0/24 via 192.168.255.2 dev eth1" > /etc/sysconfig/network-scripts/route-eth1

      - name: route add 2
        shell: echo "192.168.1.0/24 via 192.168.255.2 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1
              
      - name: route add 3
        shell: echo "192.168.2.0/24 via 192.168.255.2 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1

      - name: route add 4
        shell: echo "192.168.255.6/32 via 192.168.255.2 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1

      - name: route add 5
        shell: echo "192.168.255.10/32 via 192.168.255.2 dev eth1" >> /etc/sysconfig/network-scripts/route-eth1

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: IPtables Configuration
        command: iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE

      - name: Set ip forwarding on in /proc and verify token value with the sysctl command
        sysctl:
          name: net.ipv4.ip_forward
          value: '1'
          sysctl_set: yes

  - name: centralRouter config
    hosts: centralRouter
    become: true

    tasks:
      - name: Set ip forwarding
        shell: echo "net.ipv4.conf.all.forwarding = 1" > /etc/sysctl.d/990-sysctl.conf

      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: route add 1
        shell: echo "192.168.2.0/24 via 192.168.255.6 dev eth5" > /etc/sysconfig/network-scripts/route-eth5

      - name: route add 2
        shell: echo "192.168.1.0/24 via 192.168.255.10 dev eth6" > /etc/sysconfig/network-scripts/route-eth6

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

  - name: centralServer config
    hosts: centralServer
    become: true

    tasks:
      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

  - name: office1Router config
    hosts: office1Router
    become: true

    tasks:
      - name: Set ip forwarding
        shell: echo "net.ipv4.conf.all.forwarding = 1" > /etc/sysctl.d/990-sysctl.conf

      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.5" >> /etc/sysconfig/network-scripts/ifcfg-eth1
 
      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

  - name: office2Router config
    hosts: office2Router
    become: true

    tasks:
      - name: Set ip forwarding
        shell: echo "net.ipv4.conf.all.forwarding = 1" > /etc/sysctl.d/990-sysctl.conf

      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.255.9" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

  - name: office1Server config
    hosts: office1Server
    become: true

    tasks:
      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.2.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted

  - name: office2Server config
    hosts: office2Server
    become: true    

    tasks:
      - name: Set DEFROUTE=no
        shell: echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0

      - name: Change default gateway
        shell: echo "GATEWAY=192.168.1.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1

      - name: Restart network
        systemd:
          name: network
          state: restarted

      - name: sleep
        command: sleep 10
        
      - name: Restart network
        systemd:
          name: network
          state: restarted