---
  - name: ipaserver configuration
    hosts: ipaserver.otus.local
    become: True
    
    tasks:
    - name: install packages
      yum: name={{ item }} state=latest 
      with_items:
        - vim
        - firewalld
        - nss
        - ipa-server
        - ipa-server-dns
      
    - name: Copy file with owner and permissions
      copy:
        src: files/vagrant
        dest: /etc/sudoers.d/vagrant
        owner: root
        group: root
        mode: '0440'

    - name: Appending the user 'vagrant'to the group 'wheel'
      user:
        name: vagrant
        groups: wheel
        append: yes    
    
    - name: start the firewall
      service:
        name: firewalld 
        state: started
        enabled: true 

    - name: /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: '.*ipaserver.otus.local.*'
        line: '192.168.255.1 ipaserver.otus.local ipaserver'   

    - name: ipa-server-install
      shell:
       cmd: ipa-server-install --domain=otus.local --realm=OTUS.LOCAL --ds-password=password --admin-password=password --hostname=ipaserver.otus.local --ip-address=192.168.255.1 --reverse-zone=255.168.192.in-addr.arpa. --forwarder=8.8.8.8 --setup-dns --unattended

    - firewalld:
        service: freeipa-ldap
        permanent: yes
        immediate: yes
        state: enabled    
    
    - firewalld:
        service: freeipa-ldaps    
        permanent: yes
        immediate: yes
        state: enabled    

    - firewalld:
        service: dns
        permanent: yes
        immediate: yes
        state: enabled

  - name: ipaclient configuration
    hosts: ipaclient.otus.local
    become: True

    tasks:
    - name: install packages
      yum: name={{ item }} state=latest 
      with_items:
        - vim
        - firewalld
        - nss
        - ipa-client
              
    - name: Copy file with owner and permissions
      copy:
        src: files/vagrant
        dest: /etc/sudoers.d/vagrant
        owner: root
        group: root
        mode: '0440'

    - name: Appending the user 'vagrant'to the group 'wheel'
      user:
        name: vagrant
        groups: wheel
        append: yes    
    
    - name: start the firewall
      service:
        name: firewalld 
        state: started
        enabled: true 

    - name: /etc/hosts1
      lineinfile:
        path: /etc/hosts
        regexp: '.*ipaclient.otus.local.*'
        line: '192.168.255.2 ipaclient.otus.local ipaclient'

    - name: /etc/hosts2
      lineinfile:
        path: /etc/hosts
        regexp: '.*ipaserver.otus.local.*'
        line: '192.168.255.1 ipaserver.otus.local ipaserver'

    - name: DNS
      lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-eth1
        regexp: '^DNS1='
        line: 'DNS1="192.168.255.1"'

    - name: /etc/NetworkManager/NetworkManager.conf
      lineinfile:
        dest: /etc/NetworkManager/NetworkManager.conf
        line: 'dns=none'
        insertafter: '^\[main\]'

    - name: restart NetworkManager
      systemd:
        state: restarted
        name: NetworkManager

    - name: clear /etc/resolv.conf
      shell:
        cmd: :> /etc/resolv.conf

    - name: /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '^search'
        line: 'search otus.local'

    - name: /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        regexp: '.*nameserver 192.168.255.1.*'
        line: 'nameserver 192.168.255.1'   

    - name: ipa-client-install
      shell:
        cmd: ipa-client-install --domain 'otus.local' --principal 'admin' --password 'password' --unattended

    - name: ssh-keygen
      shell:
        cmd: ssh-keygen -q -t rsa -N 'password' -f ~/.ssh/id_rsa <<< y

    - name: kinit admin
      shell:
        cmd: echo 'password' | kinit admin    

    - name: ipa user-mod
      shell:
        cmd: ipa user-mod admin --sshpubkey="$(cat ~/.ssh/id_rsa.pub)"

    - name: AuthorizedKeysCommand
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#AuthorizedKeysCommand none'
        line: 'AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys'     

    - name: AuthorizedKeysCommandUser
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#AuthorizedKeysCommandUser'
        line: 'AuthorizedKeysCommandUser nobody'  
    
    - name: systemctl restart sshd 
      systemd:
        state: restarted
        name: sshd     
    
    - name: kdestroy
      shell:
        cmd: kdestroy