---
- hosts: VPN
  become: true
  tasks:

  - name: OpenVPN server settings
    block:
    - name: create key
      shell: openvpn --genkey --secret /etc/openvpn/static.key
    - name:  Synchronization key
      fetch:
        src: /etc/openvpn/static.key
        dest: files
    - name: configure server
      copy:
        src: tun/server.conf
        dest: /etc/openvpn/server.conf
    - name: 
      systemd:
        state: restarted
        name: openvpn@server
        enabled: yes
    when: ansible_hostname == "server"

  - name: OpenVPN client settings
    block:
    - name: configure client
      copy:
        src: tun/client.conf
        dest: /etc/openvpn/server.conf
    - name:  Synchronization key
      copy:
        src: files/server/etc/openvpn/static.key
        dest: /etc/openvpn/static.key
    - name: started server
      systemd:
        state: restarted
        name: openvpn@server
        enabled: yes
    when: ansible_hostname == "client"